# Auto-labels for PRs based on changed file paths.
# Used by .github/workflows/migration_label.yml

migration:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/response_integrations/google/**'

playbook:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/playbooks/**'

playbook-community:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/playbooks/third_party/community/**'

playbook-partner:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/playbooks/third_party/partner/**'

playbook-google:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/playbooks/google/**'

mp-tool:
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/mp/**'

community:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/response_integrations/third_party/community/**'

partner:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/response_integrations/third_party/partner/**'

power-up:
  - changed-files:
    - any-glob-to-any-file:
      - 'content/response_integrations/power_ups/**'
