# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

from .common import (
    VALID_REPEATED_FILES,
    create_dir_if_not_exists,
    create_dirs_if_not_exists,
    create_or_get_content_dir,
    create_or_get_download_dir,
    create_or_get_out_contents_dir,
    create_or_get_out_dir,
    flatten_dir,
    is_valid_source_path,
    recreate_dir,
    remove_files_by_suffix_from_dir,
    remove_paths_if_exists,
    remove_rglobs_if_exists,
    save_yaml,
)
from .integrations import (
    IntegrationParityValidator,
    base64_to_png_file,
    create_or_get_integrations_dir,
    create_or_get_integrations_path,
    create_or_get_out_integrations_dir,
    discover_core_modules,
    get_all_marketplace_integrations_paths,
    get_integration_base_folders_paths,
    get_integrations_from_paths,
    get_integrations_repo_base_path,
    get_marketplace_integration_path,
    is_built,
    is_certified_integration,
    is_half_built,
    is_integration,
    is_non_built_integration,
    is_python_file,
    load_json_file,
    load_yaml_file,
    png_path_to_bytes,
    read_and_validate_json_file,
    replace_file_content,
    svg_path_to_text,
    text_to_svg_file,
    validate_png_content,
    validate_svg_content,
    write_str_to_json_file,
    write_yaml_to_file,
)
from .playbooks import (
    create_or_get_playbooks_root_dir,
    get_display_info,
    get_or_create_playbook_repo_base_path,
    get_playbook_base_folders_paths,
    get_playbook_out_base_dir,
    get_playbook_out_dir,
    is_built_playbook,
    is_non_built_playbook,
)

__all__: list[str] = [
    "VALID_REPEATED_FILES",
    "IntegrationParityValidator",
    "base64_to_png_file",
    "create_dir_if_not_exists",
    "create_dirs_if_not_exists",
    "create_or_get_content_dir",
    "create_or_get_download_dir",
    "create_or_get_integrations_dir",
    "create_or_get_integrations_path",
    "create_or_get_out_contents_dir",
    "create_or_get_out_dir",
    "create_or_get_out_integrations_dir",
    "create_or_get_playbooks_root_dir",
    "discover_core_modules",
    "flatten_dir",
    "get_all_marketplace_integrations_paths",
    "get_display_info",
    "get_integration_base_folders_paths",
    "get_integrations_from_paths",
    "get_integrations_repo_base_path",
    "get_marketplace_integration_path",
    "get_or_create_playbook_repo_base_path",
    "get_playbook_base_folders_paths",
    "get_playbook_out_base_dir",
    "get_playbook_out_dir",
    "is_built",
    "is_built_playbook",
    "is_certified_integration",
    "is_half_built",
    "is_integration",
    "is_non_built_integration",
    "is_non_built_playbook",
    "is_python_file",
    "is_valid_source_path",
    "load_json_file",
    "load_yaml_file",
    "png_path_to_bytes",
    "read_and_validate_json_file",
    "recreate_dir",
    "remove_files_by_suffix_from_dir",
    "remove_paths_if_exists",
    "remove_rglobs_if_exists",
    "replace_file_content",
    "save_yaml",
    "svg_path_to_text",
    "text_to_svg_file",
    "validate_png_content",
    "validate_svg_content",
    "write_str_to_json_file",
    "write_yaml_to_file",
]
