name: 'Push Custom Integrations'
description: 'Push custom integrations to a SOAR environment when changes are detected in the content/response_integrations/custom/ path.'
author: 'Google SecOps Content-Hub Team'

branding:
  icon: 'upload-cloud'
  color: 'red'

inputs:
  soar_api_url:
    description: 'The API root URL of the SOAR environment.'
    required: true
  soar_api_key:
    description: 'The API key for SOAR authentication. (Recommended)'
    required: false
  soar_username:
    description: 'The username for SOAR authentication. Used if soar_api_key is not provided.'
    required: false
  soar_password:
    description: 'The password for SOAR authentication. Used if soar_api_key is not provided.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Check for changes in custom integrations'
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: content/response_integrations/custom/**

    - name: 'Set up Python'
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 'Install mp package'
      if: steps.changed-files.outputs.any_changed == 'true'
      # language=bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install ./packages/mp
      shell: bash

    - name: 'Configure MP'
      if: steps.changed-files.outputs.any_changed == 'true'
      # language=bash
      run: |
        mp config --root-path . --processes 10 --display-config
      shell: bash

    - name: 'Login to SOAR'
      env:
        SOAR_API_URL: ${{ inputs.soar_api_url }}
        SOAR_API_KEY: ${{ inputs.soar_api_key }}
        SOAR_USERNAME: ${{ inputs.soar_username }}
        SOAR_PASSWORD: ${{ inputs.soar_password }}
      id: login
      if: steps.changed-files.outputs.any_changed == 'true'
      # language=bash
      run: |
        if [ -n "$SOAR_API_KEY" ]; then
          mp login --api-root "$SOAR_API_URL" --api-key "$SOAR_API_KEY"
        elif [ -n "$SOAR_USERNAME" ] && [ -n "$SOAR_PASSWORD" ]; then
          mp login --api-root "$SOAR_API_URL" --username "$SOAR_USERNAME" --password "$SOAR_PASSWORD"
        else
          echo "Error: Missing credentials. Please provide either soar_api_key or both soar_username and soar_password."
          exit 1
        fi
      shell: bash

    - name: 'Push custom integrations'
      if: steps.changed-files.outputs.any_changed == 'true' && steps.login.outcome == 'success'
      # language=bash
      run: |
        mp push custom-integration-repository
      shell: bash
